version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: ghost-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghost
    volumes:
      - ghost-mysql-data:/var/lib/mysql

  ghost:
    image: ghost:5
    container_name: ghost-blog
    restart: always
    depends_on:
      - mysql
    ports:
      - "2368:2368"
    environment:
      url: http://localhost:2368
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ghost
      database__connection__password: ghost
      database__connection__database: ghost
    volumes:
      - ghost-content:/var/lib/ghost/content

volumes:
  ghost-mysql-data:
  ghost-content: